name = "stable-range"
version = "0.1.0"
defaultTargets = ["StableRange", "StableRangeTests"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.header = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "83abb3e776bdefcbc447a1e44d0debe4010039e5"

[[require]]
name = "general-linear-groups"
git = "https://github.com/FormalFrontier/general-linear-groups.git"
rev = "4911287aa3c1a7e9f2acb81249766f2682da58fb"

[[lean_lib]]
name = "StableRange"

[[lean_lib]]
name = "StableRangeTests"
srcDir = "tests"
roots = ["StableRangeTests"]
