/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import StableRange.CommutativeStableRange
public import Mathlib.RingTheory.Ideal.MinimalPrime.Noetherian
public import Mathlib.RingTheory.Ideal.Height
public import Mathlib.RingTheory.Ideal.Operations

/-!
# Bass stable range from Krull dimension

This file develops the finite-prime general-position argument used in Bass's
stable-range theorem for commutative noetherian rings.  The first lemma is the
finite-antichain pivot step: a coordinate may be changed by an element of the
ideal generated by the other coordinates so that it avoids every ideal in a
finite incomparable family of prime ideals.
-/

set_option warningAsError true

@[expose] public section

open scoped BigOperators

namespace Bass

universe u

variable {R : Type u} [CommRing R]

/-- Over a commutative ring, a finite row is right-unimodular exactly when
its entries generate the unit ideal. -/
theorem isRightUnimodular_iff_span_range_eq_top {n : ℕ} (row : Fin n → R) :
    IsRightUnimodular row ↔ Ideal.span (Set.range row) = ⊤ := by
  constructor
  · rintro ⟨coefficient, hcoefficient⟩
    apply (Ideal.span (Set.range row)).eq_top_iff_one.mpr
    apply Ideal.mem_span_range_iff_exists_fun.mpr
    exact ⟨coefficient, by simpa only [mul_comm] using hcoefficient⟩
  · intro htop
    have hone : (1 : R) ∈ Ideal.span (Set.range row) :=
      (Ideal.span (Set.range row)).eq_top_iff_one.mp htop
    obtain ⟨coefficient, hcoefficient⟩ :=
      Ideal.mem_span_range_iff_exists_fun.mp hone
    exact ⟨coefficient, by simpa only [mul_comm] using hcoefficient⟩

/-- A finite-antichain pivot lemma.  If the displayed elements are not all in
any prime in a finite incomparable family, one may add a linear combination of
the tail to the pivot so that the result avoids every prime in the family.

The product coefficients in the proof avoid any hypothesis on the residue
fields. -/
theorem exists_mem_span_add_avoids_finite_antichain
    {n : ℕ} (primes : Finset (Ideal R))
    (hprime : ∀ P ∈ primes, P.IsPrime)
    (hanti : ∀ P ∈ primes, ∀ Q ∈ primes, P ≠ Q → ¬ P ≤ Q)
    (pivot : R) (tail : Fin n → R)
    (havoid : ∀ P ∈ primes, pivot ∉ P ∨ ∃ i, tail i ∉ P) :
    ∃ y ∈ Ideal.span (Set.range tail),
      ∀ P ∈ primes, pivot + y ∉ P := by
  classical
  induction primes using Finset.induction_on with
  | empty =>
      exact ⟨0, Ideal.zero_mem _, by simp⟩
  | @insert P primes hP ih =>
      have hprimeP : P.IsPrime := hprime P (Finset.mem_insert_self P primes)
      have hprimeTail : ∀ Q ∈ primes, Q.IsPrime := by
        intro Q hQ
        exact hprime Q (Finset.mem_insert_of_mem hQ)
      have hantiTail :
          ∀ Q ∈ primes, ∀ Q' ∈ primes, Q ≠ Q' → ¬ Q ≤ Q' := by
        intro Q hQ Q' hQ' hne
        exact hanti Q (Finset.mem_insert_of_mem hQ) Q'
          (Finset.mem_insert_of_mem hQ') hne
      have havoidTail :
          ∀ Q ∈ primes, pivot ∉ Q ∨ ∃ i, tail i ∉ Q := by
        intro Q hQ
        exact havoid Q (Finset.mem_insert_of_mem hQ)
      obtain ⟨y, hySpan, hy⟩ := ih hprimeTail hantiTail havoidTail
      by_cases hyP : pivot + y ∈ P
      · have htailP : ∃ i, tail i ∉ P := by
          by_contra h
          have htailAll : ∀ i, tail i ∈ P := by
            simpa only [not_exists, not_not] using h
          have hspanP : Ideal.span (Set.range tail) ≤ P := by
            apply Ideal.span_le.mpr
            rintro _ ⟨i, rfl⟩
            exact htailAll i
          have hyMem : y ∈ P := hspanP hySpan
          have hpivotMem : pivot ∈ P := by
            simpa only [add_sub_cancel_right] using P.sub_mem hyP hyMem
          exact (havoid P (Finset.mem_insert_self P primes)).elim
            (fun hpivot ↦ hpivot hpivotMem) (fun hex ↦ h hex)
        choose index hindex using htailP
        have hnotle : ∀ Q ∈ primes, ¬ Q ≤ P := by
          intro Q hQ
          exact hanti Q (Finset.mem_insert_of_mem hQ) P
            (Finset.mem_insert_self P primes) (by
              rintro rfl
              exact hP hQ)
        let coefficient : {Q // Q ∈ primes} → R := fun Q ↦
          Classical.choose (Set.not_subset.mp (hnotle Q Q.property))
        have hcoefficientMem :
            ∀ Q : {Q // Q ∈ primes}, coefficient Q ∈ Q.1 := by
          intro Q
          exact (Classical.choose_spec
            (Set.not_subset.mp (hnotle Q Q.property))).1
        have hcoefficientNotMem :
            ∀ Q : {Q // Q ∈ primes}, coefficient Q ∉ P := by
          intro Q
          exact (Classical.choose_spec
            (Set.not_subset.mp (hnotle Q Q.property))).2
        let c : R := ∏ Q, coefficient Q
        have hcP : c ∉ P := by
          let _ : P.IsPrime := hprimeP
          intro hc
          rw [Ideal.IsPrime.prod_mem_iff] at hc
          obtain ⟨Q, hQ, hcoeff⟩ := hc
          exact hcoefficientNotMem Q hcoeff
        have hcTailP : c * tail index ∉ P := by
          intro hmem
          exact (hprimeP.mem_or_mem hmem).elim hcP hindex
        have hcQ : ∀ Q ∈ primes, c ∈ Q := by
          intro Q hQ
          let Q' : {Q // Q ∈ primes} := ⟨Q, hQ⟩
          have hdiv : coefficient Q' ∣ c := by
            exact Finset.dvd_prod_of_mem coefficient (Finset.mem_univ Q')
          obtain ⟨z, hz⟩ := hdiv
          rw [hz]
          exact Q.mul_mem_right z (hcoefficientMem Q')
        refine ⟨y + c * tail index, ?_, ?_⟩
        · exact (Ideal.span (Set.range tail)).add_mem hySpan
            ((Ideal.span (Set.range tail)).mul_mem_left c
              (Ideal.subset_span ⟨index, rfl⟩))
        · intro Q hQ
          rw [Finset.mem_insert] at hQ
          rcases hQ with hQP | hQ
          · subst Q
            intro hnew
            have hcorr : c * tail index ∈ P := by
              have heq :
                  pivot + (y + c * tail index) - (pivot + y) =
                    c * tail index := by ring
              rw [← heq]
              have := P.sub_mem hnew hyP
              exact this
            exact hcTailP hcorr
          · intro hnew
            have hcorr : c * tail index ∈ Q :=
              Q.mul_mem_right (tail index) (hcQ Q hQ)
            have hold : pivot + y ∈ Q := by
              have heq :
                  pivot + (y + c * tail index) - c * tail index =
                    pivot + y := by ring
              rw [← heq]
              have := Q.sub_mem hnew hcorr
              exact this
            exact hy Q hQ hold
      · refine ⟨y, hySpan, ?_⟩
        intro Q hQ
        rw [Finset.mem_insert] at hQ
        rcases hQ with rfl | hQ
        · exact hyP
        · exact hy Q hQ

/-- The ideal generated by the first `k` terms of a sequence, presented
recursively so that adjoining the next pivot is definitional. -/
def prefixIdeal (sequence : ℕ → R) : ℕ → Ideal R :=
  Nat.rec ⊥ (fun k ideal => ideal ⊔ Ideal.span {sequence k})

@[simp]
theorem prefixIdeal_zero (sequence : ℕ → R) :
    prefixIdeal sequence 0 = ⊥ := rfl

@[simp]
theorem prefixIdeal_succ (sequence : ℕ → R) (k : ℕ) :
    prefixIdeal sequence (k + 1) =
      prefixIdeal sequence k ⊔ Ideal.span {sequence k} := rfl

/-- If each new generator avoids every prime minimal over the preceding
prefix, then every prime minimal over the `k`-th prefix has height at least
`k`. -/
theorem natCast_le_height_of_mem_minimalPrimes_prefixIdeal
    (sequence : ℕ → R)
    (havoid : ∀ k P, P ∈ (prefixIdeal sequence k).minimalPrimes →
      sequence k ∉ P) :
    ∀ k P, P ∈ (prefixIdeal sequence k).minimalPrimes →
      (k : ℕ∞) ≤ P.height := by
  intro k
  induction k with
  | zero =>
      intro P hP
      simp
  | succ k ih =>
      intro Q hQ
      have hQprime : Q.IsPrime := hQ.isPrime
      have hprefixQ : prefixIdeal sequence k ≤ Q := by
        exact le_sup_left.trans hQ.le
      let _ : Q.IsPrime := hQprime
      obtain ⟨P, hP, hPQ⟩ := Ideal.exists_minimalPrimes_le hprefixQ
      have hPprime : P.IsPrime := hP.isPrime
      have hsequenceQ : sequence k ∈ Q := by
        apply hQ.le
        rw [prefixIdeal_succ]
        exact (show Ideal.span {sequence k} ≤
          prefixIdeal sequence k ⊔ Ideal.span {sequence k} from le_sup_right)
          (Ideal.subset_span (Set.mem_singleton (sequence k)))
      have hlt : P < Q := lt_of_le_of_ne hPQ (by
        intro hQP
        subst Q
        exact (havoid k P hP) hsequenceQ)
      let _ : P.IsPrime := hPprime
      have hheight := Ideal.height_add_one_le_of_lt_of_isPrime hlt
      calc
        ((k + 1 : ℕ) : ℕ∞) = (k : ℕ∞) + 1 := by simp
        _ ≤ P.height + 1 := add_le_add (ih P hP) le_rfl
        _ ≤ Q.height := hheight

/-- In Krull dimension at most `d`, a sequence of `d + 1` successive pivots
that avoid the minimal primes of every preceding prefix generates the unit
ideal. -/
theorem prefixIdeal_eq_top_of_avoids_minimalPrimes
    [Ring.KrullDimLE d R] (sequence : ℕ → R)
    (havoid : ∀ k P, P ∈ (prefixIdeal sequence k).minimalPrimes →
      sequence k ∉ P) :
    prefixIdeal sequence (d + 1) = ⊤ := by
  by_contra htop
  obtain ⟨P, hP⟩ := Ideal.nonempty_minimalPrimes htop
  have hPprime : P.IsPrime := hP.isPrime
  let _ : P.IsPrime := hPprime
  have hlower : ((d + 1 : ℕ) : ℕ∞) ≤ P.height :=
    natCast_le_height_of_mem_minimalPrimes_prefixIdeal sequence havoid
      (d + 1) P hP
  have himpossible :
      (((d + 1 : ℕ) : ℕ∞) : WithBot ℕ∞) ≤
        ((d : ℕ∞) : WithBot ℕ∞) :=
    calc
      (((d + 1 : ℕ) : ℕ∞) : WithBot ℕ∞) ≤
          (P.height : WithBot ℕ∞) := WithBot.coe_le_coe.mpr hlower
      _ ≤ ringKrullDim R := Ideal.height_le_ringKrullDim_of_isPrime
      _ ≤ ((d : ℕ∞) : WithBot ℕ∞) :=
        Ring.krullDimLE_iff.mp (inferInstance : Ring.KrullDimLE d R)
  have : d + 1 ≤ d := by exact_mod_cast himpossible
  omega

/-- Adjoining an element that avoids every minimal prime raises the lower
height bound on the minimal primes by one. -/
theorem natCast_succ_le_height_minimalPrimes_sup_span_singleton
    (I : Ideal R) (k : ℕ)
    (hheight : ∀ P, P ∈ I.minimalPrimes → (k : ℕ∞) ≤ P.height)
    (x : R) (havoid : ∀ P, P ∈ I.minimalPrimes → x ∉ P) :
    ∀ Q, Q ∈ (I ⊔ Ideal.span {x}).minimalPrimes →
      ((k + 1 : ℕ) : ℕ∞) ≤ Q.height := by
  intro Q hQ
  have hQprime : Q.IsPrime := hQ.isPrime
  have hIQ : I ≤ Q := le_sup_left.trans hQ.le
  let _ : Q.IsPrime := hQprime
  obtain ⟨P, hP, hPQ⟩ := Ideal.exists_minimalPrimes_le hIQ
  have hPprime : P.IsPrime := hP.isPrime
  have hxQ : x ∈ Q := by
    apply hQ.le
    exact (show Ideal.span {x} ≤ I ⊔ Ideal.span {x} from le_sup_right)
      (Ideal.subset_span (Set.mem_singleton x))
  have hlt : P < Q := lt_of_le_of_ne hPQ (by
    intro hQP
    subst Q
    exact (havoid P hP) hxQ)
  let _ : P.IsPrime := hPprime
  calc
    ((k + 1 : ℕ) : ℕ∞) = (k : ℕ∞) + 1 := by simp
    _ ≤ P.height + 1 := add_le_add (hheight P hP) le_rfl
    _ ≤ Q.height := Ideal.height_add_one_le_of_lt_of_isPrime hlt

/-- An ideal whose minimal primes all have height strictly above the Krull
dimension is the unit ideal. -/
theorem ideal_eq_top_of_natCast_succ_le_height_minimalPrimes
    [Ring.KrullDimLE d R] (I : Ideal R)
    (hheight : ∀ P, P ∈ I.minimalPrimes →
      ((d + 1 : ℕ) : ℕ∞) ≤ P.height) :
    I = ⊤ := by
  by_contra htop
  obtain ⟨P, hP⟩ := Ideal.nonempty_minimalPrimes htop
  have hPprime : P.IsPrime := hP.isPrime
  let _ : P.IsPrime := hPprime
  have himpossible :
      (((d + 1 : ℕ) : ℕ∞) : WithBot ℕ∞) ≤
        ((d : ℕ∞) : WithBot ℕ∞) :=
    calc
      (((d + 1 : ℕ) : ℕ∞) : WithBot ℕ∞) ≤
          (P.height : WithBot ℕ∞) := WithBot.coe_le_coe.mpr (hheight P hP)
      _ ≤ ringKrullDim R := Ideal.height_le_ringKrullDim_of_isPrime
      _ ≤ ((d : ℕ∞) : WithBot ℕ∞) :=
        Ring.krullDimLE_iff.mp (inferInstance : Ring.KrullDimLE d R)
  have : d + 1 ≤ d := by exact_mod_cast himpossible
  omega

/-- The recursive general-position step.  Starting with an ideal whose
minimal primes have height at least `k`, `n` remaining row entries suffice
when `k + n = d + 1`.  The conclusion changes each remaining entry only by a
multiple of the distinguished element. -/
private theorem exists_adjustment_span_sup_eq_top
    [IsNoetherianRing R] [Ring.KrullDimLE d R]
    (k n : ℕ) (hkn : k + n = d + 1) (I : Ideal R)
    (hheight : ∀ P, P ∈ I.minimalPrimes → (k : ℕ∞) ≤ P.height)
    (a₀ : R) (row : Fin n → R)
    (htop : I ⊔ Ideal.span {a₀} ⊔ Ideal.span (Set.range row) = ⊤) :
    ∃ t : Fin n → R,
      I ⊔ Ideal.span (Set.range fun i ↦ row i + a₀ * t i) = ⊤ := by
  classical
  induction n generalizing k I with
  | zero =>
      have hk : k = d + 1 := by omega
      have hItop : I = ⊤ :=
        ideal_eq_top_of_natCast_succ_le_height_minimalPrimes I (by
          intro P hP
          simpa only [hk] using hheight P hP)
      refine ⟨fun i ↦ Fin.elim0 i, ?_⟩
      simp [hItop]
  | succ n ih =>
      by_cases hItop : I = ⊤
      · refine ⟨fun _ ↦ 0, ?_⟩
        simp [hItop]
      · let allPrimes : Finset (Ideal R) :=
          I.finite_minimalPrimes_of_isNoetherianRing R |>.toFinset
        let containing : Finset (Ideal R) :=
          allPrimes.filter fun P ↦ a₀ ∈ P
        let notContaining : Finset (Ideal R) :=
          allPrimes.filter fun P ↦ a₀ ∉ P
        have hmemAll : ∀ P, P ∈ allPrimes ↔ P ∈ I.minimalPrimes := by
          intro P
          simp [allPrimes]
        have hmemContaining :
            ∀ P, P ∈ containing ↔ P ∈ I.minimalPrimes ∧ a₀ ∈ P := by
          intro P
          simp [containing, hmemAll]
        have hmemNotContaining :
            ∀ P, P ∈ notContaining ↔ P ∈ I.minimalPrimes ∧ a₀ ∉ P := by
          intro P
          simp [notContaining, hmemAll]
        have hprimeContaining : ∀ P ∈ containing, P.IsPrime := by
          intro P hP
          exact (hmemContaining P).mp hP |>.1.isPrime
        have hprimeNotContaining : ∀ P ∈ notContaining, P.IsPrime := by
          intro P hP
          exact (hmemNotContaining P).mp hP |>.1.isPrime
        have hantiMinimal :
            ∀ P, P ∈ I.minimalPrimes → ∀ Q, Q ∈ I.minimalPrimes →
              P ≠ Q → ¬ P ≤ Q := by
          intro P hP Q hQ hne hPQ
          exact hne (le_antisymm hPQ (hQ.2 hP.1 hPQ))
        have hantiContaining :
            ∀ P ∈ containing, ∀ Q ∈ containing, P ≠ Q → ¬ P ≤ Q := by
          intro P hP Q hQ
          exact hantiMinimal P ((hmemContaining P).mp hP).1 Q
            ((hmemContaining Q).mp hQ).1
        have hantiNotContaining :
            ∀ P ∈ notContaining, ∀ Q ∈ notContaining,
              P ≠ Q → ¬ P ≤ Q := by
          intro P hP Q hQ
          exact hantiMinimal P ((hmemNotContaining P).mp hP).1 Q
            ((hmemNotContaining Q).mp hQ).1
        let pivot : R := row 0
        let tail : Fin n → R := fun i ↦ row i.succ
        have havoidContaining :
            ∀ P ∈ containing, pivot ∉ P ∨ ∃ i, tail i ∉ P := by
          intro P hP
          by_cases hpivot : pivot ∈ P
          · right
            by_contra htail
            have htailAll : ∀ i, tail i ∈ P := by
              simpa only [not_exists, not_not] using htail
            have hPmin := ((hmemContaining P).mp hP).1
            have ha₀P := ((hmemContaining P).mp hP).2
            have hrowSpan : Ideal.span (Set.range row) ≤ P := by
              apply Ideal.span_le.mpr
              rintro _ ⟨i, rfl⟩
              refine Fin.cases hpivot ?_ i
              intro j
              exact htailAll j
            have htopP : (⊤ : Ideal R) ≤ P := by
              rw [← htop]
              exact sup_le (sup_le hPmin.le
                (Ideal.span_le.mpr (by simpa))) hrowSpan
            exact hPmin.isPrime.ne_top (top_unique htopP)
          · exact Or.inl hpivot
        obtain ⟨y, hySpan, hyAvoid⟩ :=
          exists_mem_span_add_avoids_finite_antichain containing
            hprimeContaining hantiContaining pivot tail havoidContaining
        obtain ⟨coefficient, hcoefficient⟩ :=
          (Ideal.mem_span_range_iff_exists_fun).mp hySpan
        have havoidNotContaining :
            ∀ P ∈ notContaining, pivot + y ∉ P ∨
              ∃ i : Fin 1, (fun _ ↦ a₀) i ∉ P := by
          intro P hP
          exact Or.inr ⟨0, (hmemNotContaining P).mp hP |>.2⟩
        obtain ⟨z, hzSpan, hzAvoid⟩ :=
          exists_mem_span_add_avoids_finite_antichain notContaining
            hprimeNotContaining hantiNotContaining (pivot + y)
            (fun _ : Fin 1 ↦ a₀) havoidNotContaining
        obtain ⟨scalarCoefficient, hscalarCoefficient⟩ :=
          (Ideal.mem_span_range_iff_exists_fun).mp hzSpan
        let scalar : R := scalarCoefficient 0
        have hz : z = a₀ * scalar := by
          simpa only [Fin.sum_univ_one, scalar, mul_comm] using
            hscalarCoefficient.symm
        let nextPivot : R := pivot + y + z
        have hnextAvoid :
            ∀ P, P ∈ I.minimalPrimes → nextPivot ∉ P := by
          intro P hP
          by_cases ha₀P : a₀ ∈ P
          · have hPcont : P ∈ containing :=
              (hmemContaining P).mpr ⟨hP, ha₀P⟩
            intro hnext
            have hzP : z ∈ P := by
              rw [hz]
              exact P.mul_mem_right scalar ha₀P
            have : pivot + y ∈ P := by
              have := P.sub_mem hnext hzP
              simpa only [nextPivot, add_sub_cancel_right] using this
            exact hyAvoid P hPcont this
          · exact hzAvoid P ((hmemNotContaining P).mpr ⟨hP, ha₀P⟩)
        let nextIdeal : Ideal R := I ⊔ Ideal.span {nextPivot}
        have hheightNext :
            ∀ P, P ∈ nextIdeal.minimalPrimes →
              ((k + 1 : ℕ) : ℕ∞) ≤ P.height := by
          simpa only [nextIdeal] using
            natCast_succ_le_height_minimalPrimes_sup_span_singleton
              I k hheight nextPivot hnextAvoid
        let nextTarget : Ideal R :=
          nextIdeal ⊔ Ideal.span {a₀} ⊔ Ideal.span (Set.range tail)
        have hNextIdealTarget : nextIdeal ≤ nextTarget := by
          exact le_sup_left.trans le_sup_left
        have ha₀Target : Ideal.span {a₀} ≤ nextTarget := by
          exact le_sup_right.trans le_sup_left
        have htailTarget : Ideal.span (Set.range tail) ≤ nextTarget :=
          le_sup_right
        have htopNext :
            nextIdeal ⊔ Ideal.span {a₀} ⊔ Ideal.span (Set.range tail) = ⊤ := by
          change nextTarget = ⊤
          apply top_unique
          rw [← htop]
          apply sup_le
          · apply sup_le
            · exact (show I ≤ nextIdeal from le_sup_left).trans hNextIdealTarget
            · exact ha₀Target
          · apply Ideal.span_le.mpr
            rintro _ ⟨i, rfl⟩
            refine Fin.cases ?_ (fun j ↦ ?_) i
            · have hnextMem : nextPivot ∈ nextTarget := by
                exact hNextIdealTarget
                  ((show Ideal.span {nextPivot} ≤ nextIdeal from le_sup_right)
                    (Ideal.subset_span (Set.mem_singleton nextPivot)))
              have hyMem : y ∈ nextTarget := htailTarget hySpan
              have hzMem : z ∈ nextTarget := by
                rw [hz]
                exact nextTarget.mul_mem_right scalar
                  (ha₀Target (Ideal.subset_span (Set.mem_singleton a₀)))
              have := nextTarget.sub_mem
                (nextTarget.sub_mem hnextMem hzMem) hyMem
              change pivot ∈ nextTarget
              have hpivotEq : pivot = nextPivot - z - y := by
                simp only [nextPivot, add_sub_cancel_right]
              rw [hpivotEq]
              exact this
            · exact htailTarget (Ideal.subset_span ⟨j, rfl⟩)
        have hknNext : (k + 1) + n = d + 1 := by omega
        obtain ⟨tailAdjustment, htailAdjustment⟩ :=
          ih (k + 1) hknNext nextIdeal hheightNext tail htopNext
        let correction : R := ∑ i, coefficient i * tailAdjustment i
        let firstAdjustment : R := scalar - correction
        let adjustment : Fin (n + 1) → R :=
          Fin.cases firstAdjustment tailAdjustment
        let adjustedTail : Fin n → R :=
          fun i ↦ tail i + a₀ * tailAdjustment i
        let adjustedRow : Fin (n + 1) → R :=
          fun i ↦ row i + a₀ * adjustment i
        have hadjustedRowZero :
            adjustedRow 0 = pivot + a₀ * firstAdjustment := by
          simp [adjustedRow, adjustment, pivot]
        have hadjustedRowSucc :
            ∀ i, adjustedRow i.succ = adjustedTail i := by
          intro i
          simp [adjustedRow, adjustment, adjustedTail, tail]
        have hsumAdjusted :
            ∑ i, coefficient i * adjustedTail i = y + a₀ * correction := by
          calc
            ∑ i, coefficient i * adjustedTail i =
                (∑ i, coefficient i * tail i) +
                  a₀ * (∑ i, coefficient i * tailAdjustment i) := by
                    rw [Finset.mul_sum]
                    rw [← Finset.sum_add_distrib]
                    apply Finset.sum_congr rfl
                    intro i hi
                    simp only [adjustedTail]
                    ring
            _ = y + a₀ * correction := by
              rw [hcoefficient]
        have hnextPivotCombination :
            nextPivot = adjustedRow 0 +
              ∑ i, coefficient i * adjustedRow i.succ := by
          rw [hadjustedRowZero]
          simp_rw [hadjustedRowSucc]
          rw [hsumAdjusted]
          simp only [nextPivot]
          rw [hz]
          simp only [firstAdjustment]
          ring
        refine ⟨adjustment, ?_⟩
        change I ⊔ Ideal.span (Set.range adjustedRow) = ⊤
        apply top_unique
        rw [← htailAdjustment]
        apply sup_le
        · change I ⊔ Ideal.span {nextPivot} ≤
            I ⊔ Ideal.span (Set.range adjustedRow)
          apply sup_le
          · exact le_sup_left
          · apply Ideal.span_le.mpr
            intro x hx
            rw [Set.mem_singleton_iff] at hx
            subst x
            rw [hnextPivotCombination]
            apply (I ⊔ Ideal.span (Set.range adjustedRow)).add_mem
            · exact (show Ideal.span (Set.range adjustedRow) ≤
                I ⊔ Ideal.span (Set.range adjustedRow) from le_sup_right)
                (Ideal.subset_span ⟨0, rfl⟩)
            · exact Submodule.sum_mem _ fun i _ ↦
                (I ⊔ Ideal.span (Set.range adjustedRow)).mul_mem_left
                  (coefficient i)
                  ((show Ideal.span (Set.range adjustedRow) ≤
                      I ⊔ Ideal.span (Set.range adjustedRow) from le_sup_right)
                    (Ideal.subset_span ⟨i.succ, rfl⟩))
        · apply Ideal.span_le.mpr
          rintro _ ⟨i, rfl⟩
          change adjustedTail i ∈ I ⊔ Ideal.span (Set.range adjustedRow)
          rw [← hadjustedRowSucc i]
          exact (show Ideal.span (Set.range adjustedRow) ≤
              I ⊔ Ideal.span (Set.range adjustedRow) from le_sup_right)
            (Ideal.subset_span ⟨i.succ, rfl⟩)

/-- **Bass's dimension theorem.** A commutative noetherian ring of Krull
dimension at most `d` satisfies Bass's stable-range condition `(S_(d+1))`.

The theorem includes the zero ring and does not require reducedness,
nontriviality, decidable equality, or any hypothesis on residue fields. -/
theorem stableRangeCondition_succ_of_krullDimLE
    [IsNoetherianRing R] [Ring.KrullDimLE d R] :
    StableRangeCondition R (d + 1) := by
  intro a₀ row hrow
  let initialIdeal : Ideal R :=
    (⊥ : Ideal R) ⊔ Ideal.span {a₀} ⊔ Ideal.span (Set.range row)
  have hInitialTop : initialIdeal = ⊤ := by
    apply initialIdeal.eq_top_iff_one.mpr
    obtain ⟨coefficient₀, coefficient, hcoefficient⟩ := hrow
    have ha₀ : a₀ * coefficient₀ ∈ Ideal.span {a₀} :=
      (Ideal.span {a₀}).mul_mem_right coefficient₀
        (Ideal.subset_span (Set.mem_singleton a₀))
    have htail : ∑ i, row i * coefficient i ∈
        Ideal.span (Set.range row) := by
      apply Ideal.mem_span_range_iff_exists_fun.mpr
      exact ⟨coefficient, by simp only [mul_comm]⟩
    rw [← hcoefficient]
    exact initialIdeal.add_mem
      ((show Ideal.span {a₀} ≤ initialIdeal from
        le_sup_right.trans le_sup_left) ha₀)
      ((show Ideal.span (Set.range row) ≤ initialIdeal from le_sup_right) htail)
  have hheight : ∀ P, P ∈ (⊥ : Ideal R).minimalPrimes →
      (0 : ℕ∞) ≤ P.height := by
    simp
  obtain ⟨adjustment, hadjustment⟩ :=
    exists_adjustment_span_sup_eq_top (d := d) 0 (d + 1) (by omega)
      (⊥ : Ideal R) hheight a₀ row (by simpa only [initialIdeal] using hInitialTop)
  have hspan : Ideal.span
      (Set.range fun i ↦ row i + a₀ * adjustment i) = ⊤ := by
    simpa using hadjustment
  refine ⟨fun i ↦ -adjustment i, ?_⟩
  apply (isRightUnimodular_iff_span_range_eq_top _).mpr
  simpa only [mul_neg, sub_neg_eq_add] using hspan

end Bass
