/-
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Formal Frontier Agents
-/
module

public import StableRange.Regular
public import Mathlib.RingTheory.Flat.Localization
public import Mathlib.RingTheory.KrullDimension.Zero
public import Mathlib.RingTheory.LocalProperties.Reduced
import Mathlib.LinearAlgebra.Basis.VectorSpace

/-!
# Commutative von Neumann regular rings

This file characterizes commutative von Neumann regular rings as the reduced
rings of Krull dimension at most zero. It also proves their absolute-flatness
property: every module over such a ring is flat.
-/

set_option warningAsError true

@[expose] public section

namespace Bass

universe u v

variable {R : Type u} [CommRing R]

/-- A commutative von Neumann regular ring has no nonzero nilpotents. -/
theorem IsVonNeumannRegular.isReduced (hreg : IsVonNeumannRegular R) :
    IsReduced R := by
  rw [isReduced_iff_pow_one_lt 2 one_lt_two]
  intro r hr
  obtain ⟨x, hx⟩ := hreg r
  calc
    r = r * x * r := hx
    _ = x * r ^ 2 := by ring
    _ = 0 := by rw [hr, mul_zero]

/-- Every prime ideal of a commutative von Neumann regular ring is maximal. -/
theorem IsVonNeumannRegular.krullDimLE_zero
    (hreg : IsVonNeumannRegular R) : Ring.KrullDimLE 0 R := by
  rw [Ring.krullDimLE_zero_iff]
  intro I hI
  rw [Ideal.isMaximal_iff]
  refine ⟨hI.one_notMem, ?_⟩
  intro J r hIJ hrI hrJ
  obtain ⟨x, hx⟩ := hreg r
  have hfactor : r * (1 - x * r) ∈ I := by
    have : r * (1 - x * r) = 0 := by
      rw [mul_sub, mul_one, ← mul_assoc, ← hx, sub_self]
    rw [this]
    exact I.zero_mem
  have hcomplementI : 1 - x * r ∈ I :=
    (hI.mem_or_mem hfactor).resolve_left hrI
  have hcomplementJ : 1 - x * r ∈ J := hIJ hcomplementI
  have hxrJ : x * r ∈ J := J.mul_mem_left x hrJ
  have := J.add_mem hcomplementJ hxrJ
  simpa using this

/-- In a reduced zero-dimensional commutative ring, the principal ideals
generated by `r` and `r ^ 2` coincide. -/
theorem span_sq_eq_span_of_isReduced_krullDimLE_zero
    [IsReduced R] [Ring.KrullDimLE 0 R] (r : R) :
    Ideal.span ({r ^ 2} : Set R) = Ideal.span {r} := by
  apply Ideal.eq_of_localization_maximal
  intro P hP
  let _ : P.IsMaximal := hP
  let _ : P.IsPrime := hP.isPrime
  have hPmin : P ∈ minimalPrimes R :=
    P.mem_minimalPrimes_of_krullDimLE_zero
  let _ : Ring.KrullDimLE 0 (Localization.AtPrime P) :=
    Ring.KrullDimLE.of_isLocalization P hPmin _
  have hfield : IsField (Localization.AtPrime P) :=
    Ring.KrullDimLE.isField_of_isReduced
  let _ : Field (Localization.AtPrime P) := hfield.toField
  simp only [Ideal.map_span, Set.image_singleton, map_pow]
  by_cases hr : algebraMap R (Localization.AtPrime P) r = 0
  · simp [hr]
  · rw [Ideal.span_singleton_eq_top.mpr
          (isUnit_iff_ne_zero.mpr (pow_ne_zero 2 hr)),
        Ideal.span_singleton_eq_top.mpr (isUnit_iff_ne_zero.mpr hr)]

/-- A reduced commutative ring of Krull dimension at most zero is von
Neumann regular. -/
theorem isVonNeumannRegular_of_isReduced_krullDimLE_zero
    [IsReduced R] [Ring.KrullDimLE 0 R] : IsVonNeumannRegular R := by
  intro r
  have hr : r ∈ Ideal.span ({r ^ 2} : Set R) := by
    rw [span_sq_eq_span_of_isReduced_krullDimLE_zero r]
    exact Ideal.mem_span_singleton_self r
  rw [Ideal.mem_span_singleton] at hr
  obtain ⟨x, hx⟩ := hr
  refine ⟨x, ?_⟩
  calc
    r = r ^ 2 * x := hx
    _ = r * x * r := by ring

/-- A commutative ring is von Neumann regular exactly when it is reduced and
has Krull dimension at most zero. -/
theorem isVonNeumannRegular_iff_isReduced_and_krullDimLE_zero :
    IsVonNeumannRegular R ↔ IsReduced R ∧ Ring.KrullDimLE 0 R := by
  constructor
  · intro hreg
    exact ⟨hreg.isReduced, hreg.krullDimLE_zero⟩
  · rintro ⟨hred, hdim⟩
    let _ : IsReduced R := hred
    let _ : Ring.KrullDimLE 0 R := hdim
    exact isVonNeumannRegular_of_isReduced_krullDimLE_zero

/-- Every module over a reduced zero-dimensional commutative ring is flat. -/
theorem flat_of_isReduced_krullDimLE_zero
    (M : Type v) [AddCommGroup M] [Module R M]
    [IsReduced R] [Ring.KrullDimLE 0 R] : Module.Flat R M := by
  apply Module.flat_of_localized_maximal
  intro P hP
  let _ : P.IsMaximal := hP
  let _ : P.IsPrime := hP.isPrime
  have hPmin : P ∈ minimalPrimes R :=
    P.mem_minimalPrimes_of_krullDimLE_zero
  let _ : Ring.KrullDimLE 0 (Localization.AtPrime P) :=
    Ring.KrullDimLE.of_isLocalization P hPmin _
  have hfield : IsField (Localization.AtPrime P) :=
    Ring.KrullDimLE.isField_of_isReduced
  let _ : Field (Localization.AtPrime P) := hfield.toField
  exact Module.Flat.trans R (Localization.AtPrime P)
    (LocalizedModule P.primeCompl M)

/-- Every module over a commutative von Neumann regular ring is flat. -/
theorem IsVonNeumannRegular.flat (hreg : IsVonNeumannRegular R)
    (M : Type v) [AddCommGroup M] [Module R M] : Module.Flat R M := by
  let _ : IsReduced R := hreg.isReduced
  let _ : Ring.KrullDimLE 0 R := hreg.krullDimLE_zero
  exact flat_of_isReduced_krullDimLE_zero M

end Bass
