/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import StableRange.Basic
public import Mathlib.Algebra.Module.Opposite
public import Mathlib.Algebra.Module.Submodule.Lattice
public import Mathlib.Algebra.Ring.Idempotent
public import Mathlib.LinearAlgebra.Finsupp.Defs
import StableRange.Local
import Mathlib.Tactic.NoncommRing

/-!
# Direct finiteness and regular rings of stable range one

This file develops applications of Bass's right stable-range-one condition
for arbitrary, possibly noncommutative rings. First, `(S_1)` makes the
multiplicative monoid Dedekind-finite. Second, a ring is unit-regular if and
only if it is von Neumann-regular and satisfies `(S_1)`. It also represents
principal right ideals as submodules of the right regular module and proves
that an inner inverse supplies an explicit complementary principal right
ideal.
-/

set_option warningAsError true

@[expose] public section

namespace Bass

universe u v

variable {R : Type u} [Ring R]

/-- Bass's condition `(S_1)` makes every one-sided inverse two-sided. -/
theorem stableRangeCondition_one_isDedekindFinite
    (h : StableRangeCondition R 1) : IsDedekindFiniteMonoid R where
  mul_eq_one_symm {a b} hab := by
    let tail : Fin 1 → R := fun _ ↦ b
    have hCons : IsRightUnimodularCons (1 - b * a) tail := by
      refine ⟨1, fun _ ↦ a, ?_⟩
      simp only [Fin.sum_univ_one, tail, mul_one]
      noncomm_ring [hab]
    obtain ⟨t, w, hw⟩ := h (1 - b * a) tail hCons
    let c : R := b - (1 - b * a) * t 0
    have hcw : c * w 0 = 1 := by
      simpa only [IsRightUnimodular, Fin.sum_univ_one, tail, c] using hw
    have hac : a * c = 1 := by
      dsimp only [c]
      calc
        a * (b - (1 - b * a) * t 0) =
            a * b - (a - a * b * a) * t 0 := by noncomm_ring
        _ = 1 := by rw [hab]; simp
    have hca : c * a = 1 := by
      have haw : a = w 0 := by
        calc
          a = a * 1 := by rw [mul_one]
          _ = a * (c * w 0) := by rw [hcw]
          _ = (a * c) * w 0 := by rw [mul_assoc]
          _ = w 0 := by rw [hac, one_mul]
      rw [haw, hcw]
    have hcb : c = b := by
      calc
        c = c * 1 := by rw [mul_one]
        _ = c * (a * b) := by rw [hab]
        _ = (c * a) * b := by rw [mul_assoc]
        _ = b := by rw [hca, one_mul]
    rw [← hcb, hca]

/-- Under `(S_1)`, an element with a right inverse is a unit. -/
theorem isUnit_of_mul_eq_one_of_stableRangeCondition_one
    (h : StableRangeCondition R 1) {a b : R} (hab : a * b = 1) :
    IsUnit a := by
  have hba := (stableRangeCondition_one_isDedekindFinite h).mul_eq_one_symm hab
  exact isUnit_iff_exists.mpr ⟨b, hab, hba⟩

/-- At index one, a right-unimodular pair can be shortened to a unit. -/
theorem stableRangeCondition_one_iff_forall_isUnit_sub_mul :
    StableRangeCondition R 1 ↔
      ∀ a b : R, (∃ s w : R, a * s + b * w = 1) →
        ∃ t : R, IsUnit (b - a * t) := by
  constructor
  · intro h a b hpair
    obtain ⟨s, w, hw⟩ := hpair
    obtain ⟨t, witness, hwitness⟩ :=
      h a (fun _ : Fin 1 ↦ b) ⟨s, fun _ ↦ w, by simpa only [Fin.sum_univ_one] using hw⟩
    refine ⟨t 0, isUnit_of_mul_eq_one_of_stableRangeCondition_one h
      (a := b - a * t 0) (b := witness 0) ?_⟩
    simpa only [IsRightUnimodular, Fin.sum_univ_one] using hwitness
  · intro h a b hpair
    obtain ⟨s, w, hw⟩ := hpair
    obtain ⟨t, hunit⟩ := h a (b 0) ⟨s, w 0, by simpa only [Fin.sum_univ_one] using hw⟩
    obtain ⟨inverse, hinverse, _⟩ := isUnit_iff_exists.mp hunit
    refine ⟨fun _ ↦ t, fun _ ↦ inverse, ?_⟩
    simpa only [IsRightUnimodular, Fin.sum_univ_one] using hinverse

/-- A ring is von Neumann-regular when every element has an inner inverse. -/
def IsVonNeumannRegular (R : Type u) [Ring R] : Prop :=
  ∀ a : R, ∃ x : R, a = a * x * a

/-- The principal right ideal `aR`, represented as a submodule of the right
regular module. The scalar action is `op(b) • y = y * b`. -/
def principalRightIdeal (a : R) : Submodule Rᵐᵒᵖ R where
  carrier := {y | ∃ b : R, a * b = y}
  zero_mem' := ⟨0, mul_zero a⟩
  add_mem' := by
    rintro y z ⟨b, rfl⟩ ⟨c, rfl⟩
    exact ⟨b + c, mul_add a b c⟩
  smul_mem' := by
    rintro b y ⟨c, rfl⟩
    refine ⟨c * b.unop, ?_⟩
    rw [MulOpposite.smul_eq_mul_unop, mul_assoc]

@[simp]
theorem mem_principalRightIdeal {a y : R} :
    y ∈ principalRightIdeal a ↔ ∃ b : R, a * b = y :=
  Iff.rfl

/-- An inner inverse for `a` makes `a * x` idempotent. -/
theorem isIdempotentElem_mul_innerInverse {a x : R} (h : a = a * x * a) :
    IsIdempotentElem (a * x) := by
  calc
    (a * x) * (a * x) = (a * x * a) * x := by simp only [mul_assoc]
    _ = a * x := by rw [← h]

/-- The right ideals generated by an idempotent and its complement are
complementary submodules of the right regular module. -/
theorem principalRightIdeals_isCompl_of_isIdempotentElem {e : R}
    (he : IsIdempotentElem e) :
    IsCompl (principalRightIdeal e) (principalRightIdeal (1 - e)) := by
  constructor
  · rw [Submodule.disjoint_def]
    intro y hyE hyC
    obtain ⟨a, ha⟩ := hyE
    obtain ⟨b, hb⟩ := hyC
    have hey : e * y = y := by
      calc
        e * y = e * (e * a) := by rw [ha]
        _ = (e * e) * a := by rw [mul_assoc]
        _ = e * a := by rw [he.eq]
        _ = y := ha
    have hec : e * y = 0 := by
      calc
        e * y = e * ((1 - e) * b) := by rw [hb]
        _ = (e * (1 - e)) * b := by rw [mul_assoc]
        _ = 0 := by rw [he.mul_one_sub_self, zero_mul]
    exact hey.symm.trans hec
  · rw [codisjoint_iff]
    apply top_unique
    intro y _
    rw [Submodule.mem_sup]
    refine ⟨e * y, ⟨y, rfl⟩, (1 - e) * y, ⟨y, rfl⟩, ?_⟩
    noncomm_ring

/-- Multiplying a generator by one of its inner inverses does not change its
principal right ideal. -/
theorem principalRightIdeal_eq_mul_innerInverse {a x : R}
    (h : a = a * x * a) :
    principalRightIdeal a = principalRightIdeal (a * x) := by
  ext y
  simp only [mem_principalRightIdeal]
  constructor
  · rintro ⟨b, rfl⟩
    refine ⟨a * b, ?_⟩
    calc
      (a * x) * (a * b) = (a * x * a) * b := by simp only [mul_assoc]
      _ = a * b := by rw [← h]
  · rintro ⟨b, rfl⟩
    exact ⟨x * b, by rw [mul_assoc]⟩

/-- If `x` is an inner inverse for `a`, then `aR` and `(1 - a*x)R` are
complementary principal right ideals. -/
theorem principalRightIdeals_isCompl_of_innerInverse {a x : R}
    (h : a = a * x * a) :
    IsCompl (principalRightIdeal a) (principalRightIdeal (1 - a * x)) := by
  rw [principalRightIdeal_eq_mul_innerInverse h]
  exact principalRightIdeals_isCompl_of_isIdempotentElem
    (isIdempotentElem_mul_innerInverse h)

/-- A ring is unit-regular when every element has an inner inverse which is a
unit. -/
def IsUnitRegular (R : Type u) [Ring R] : Prop :=
  ∀ a : R, ∃ x : Rˣ, a = a * (x : R) * a

/-- Every unit-regular ring is von Neumann-regular. -/
theorem IsUnitRegular.isVonNeumannRegular (h : IsUnitRegular R) :
    IsVonNeumannRegular R := by
  intro a
  obtain ⟨u, hu⟩ := h a
  exact ⟨u, hu⟩

/-- Every element of a von Neumann-regular ring generates a principal right
ideal with an explicit complementary principal right ideal. -/
theorem IsVonNeumannRegular.exists_principalRightIdeals_isCompl
    (h : IsVonNeumannRegular R) (a : R) :
    ∃ x : R,
      IsCompl (principalRightIdeal a) (principalRightIdeal (1 - a * x)) := by
  obtain ⟨x, hx⟩ := h a
  exact ⟨x, principalRightIdeals_isCompl_of_innerInverse hx⟩

/-- Every unit-regular ring satisfies Bass's condition `(S_1)`. -/
theorem IsUnitRegular.stableRangeCondition_one (h : IsUnitRegular R) :
    StableRangeCondition R 1 := by
  intro a r hr
  obtain ⟨x, y, hxy⟩ := hr
  let b : R := r 0
  have hab : a * x + b * y 0 = 1 := by
    simpa only [Fin.sum_univ_one, b] using hxy
  obtain ⟨v, hv⟩ := h b
  let e : R := b * (v : R)
  have he : e * e = e := by
    dsimp only [e]
    calc
      (b * (v : R)) * (b * (v : R)) =
          (b * (v : R) * b) * (v : R) := by simp only [mul_assoc]
      _ = b * (v : R) := by rw [← hv]
  have heb : e * b = b := by
    dsimp only [e]
    simpa only [mul_assoc] using hv.symm
  have hzero : (1 - e) * b = 0 := by
    rw [sub_mul, one_mul, heb, sub_self]
  have hbottom : (1 - e) * a * x = 1 - e := by
    calc
      (1 - e) * a * x = (1 - e) * (a * x) := by rw [mul_assoc]
      _ = (1 - e) * (a * x + b * y 0) := by
        rw [mul_add, ← mul_assoc (1 - e) b, hzero, zero_mul, add_zero]
      _ = 1 - e := by rw [hab, mul_one]
  let n : R := e * a * x * (1 - e)
  have horth : (1 - e) * e = 0 := by
    noncomm_ring [he]
  have hn : n * n = 0 := by
    dsimp only [n]
    calc
      (e * a * x * (1 - e)) * (e * a * x * (1 - e)) =
          e * a * x * ((1 - e) * e) * a * x * (1 - e) := by
            noncomm_ring
      _ = 0 := by rw [horth]; simp
  let q : Rˣ := ⟨1 + n, 1 - n, by noncomm_ring [hn], by noncomm_ring [hn]⟩
  have hax : a * x = e * a * x + (1 - e) := by
    calc
      a * x = e * a * x + (1 - e) * a * x := by noncomm_ring
      _ = e * a * x + (1 - e) := by rw [hbottom]
  have hq : (q : R) = e + a * x * (1 - e) := by
    dsimp only [q, n]
    rw [hax]
    noncomm_ring [he]
  let t : R := -x * (1 - e) * ((v⁻¹ : Rˣ) : R)
  have ht : t * (v : R) = -x * (1 - e) := by
    dsimp only [t]
    rw [mul_assoc, Units.inv_mul]
    simp
  have hmul : (b - a * t) * (v : R) = (q : R) := by
    rw [sub_mul, mul_assoc a t, ht, hq]
    dsimp only [e]
    noncomm_ring
  refine ⟨fun _ ↦ t, ?_⟩
  refine ⟨fun _ ↦ (v : R) * ((q⁻¹ : Rˣ) : R), ?_⟩
  rw [Fin.sum_univ_one]
  change (b - a * t) * ((v : R) * ((q⁻¹ : Rˣ) : R)) = 1
  calc
    (b - a * t) * ((v : R) * ((q⁻¹ : Rˣ) : R)) =
        ((b - a * t) * (v : R)) * ((q⁻¹ : Rˣ) : R) := by rw [mul_assoc]
    _ = (q : R) * ((q⁻¹ : Rˣ) : R) := by rw [hmul]
    _ = 1 := q.val_inv

/-- Every unit-regular ring is Dedekind-finite. -/
theorem IsUnitRegular.isDedekindFinite (h : IsUnitRegular R) :
    IsDedekindFiniteMonoid R :=
  stableRangeCondition_one_isDedekindFinite h.stableRangeCondition_one

/-- The endomorphism ring of a countable direct sum of copies of a nonzero
module is not unit-regular. -/
theorem not_isUnitRegular_moduleEnd_finsupp_nat
    (S : Type u) (M : Type v) [Semiring S] [AddCommGroup M] [Module S M]
    [Nontrivial M] :
    ¬ IsUnitRegular (Module.End S (ℕ →₀ M)) := by
  let forward : Module.End S (ℕ →₀ M) :=
    Finsupp.lmapDomain M S Nat.succ
  let backward : Module.End S (ℕ →₀ M) :=
    Finsupp.lcomapDomain (R := S) (M := M) Nat.succ Nat.succ_injective
  have hBackwardForward : backward * forward = 1 := by
    apply LinearMap.ext
    intro v
    simpa [backward, forward, Module.End.mul_apply] using
      (Finsupp.leftInverse_lcomapDomain_mapDomain
        (R := S) (M := M) Nat.succ Nat.succ_injective v)
  have hForwardBackward : forward * backward ≠ 1 := by
    obtain ⟨m, hm⟩ := exists_ne (0 : M)
    intro h
    have happ := LinearMap.congr_fun h (Finsupp.single 0 m)
    have hcoord := congrArg (fun v : ℕ →₀ M ↦ v 0) happ
    exact hm <| by
      simpa [forward, backward, Module.End.mul_apply] using hcoord.symm
  intro h
  exact hForwardBackward
    (h.isDedekindFinite.mul_eq_one_symm hBackwardForward)

/-- Every nontrivial unit-regular ring has least Bass stable range one. -/
theorem IsUnitRegular.stableRange_one [Nontrivial R] (h : IsUnitRegular R) :
    IsStableRange R 1 := by
  refine ⟨h.stableRangeCondition_one, ?_⟩
  intro n hn
  cases n with
  | zero => exact (not_stableRangeCondition_zero hn).elim
  | succ n => exact Nat.succ_le_succ (Nat.zero_le n)

/-- A von Neumann-regular ring satisfying `(S_1)` is unit-regular. -/
theorem isUnitRegular_of_stableRangeCondition_one
    (hreg : IsVonNeumannRegular R)
    (hsr : StableRangeCondition R 1) :
    IsUnitRegular R := by
  intro a
  obtain ⟨x, hx⟩ := hreg a
  let tail : Fin 1 → R := fun _ ↦ x
  have hCons : IsRightUnimodularCons (1 - x * a) tail := by
    refine ⟨1, fun _ ↦ a, ?_⟩
    simp only [Fin.sum_univ_one, tail, mul_one]
    noncomm_ring
  obtain ⟨t, w, hw⟩ := hsr (1 - x * a) tail hCons
  let u : R := x - (1 - x * a) * t 0
  have huw : u * w 0 = 1 := by
    simpa only [IsRightUnimodular, Fin.sum_univ_one, tail, u] using hw
  have hwu : w 0 * u = 1 :=
    (stableRangeCondition_one_isDedekindFinite hsr).mul_eq_one_symm huw
  let unit : Rˣ := ⟨u, w 0, huw, hwu⟩
  refine ⟨unit, ?_⟩
  have hzero : a * (1 - x * a) = 0 := by
    calc
      a * (1 - x * a) = a - a * x * a := by noncomm_ring
      _ = 0 := by rw [← hx, sub_self]
  change a = a * u * a
  dsimp only [u]
  calc
    a = a * x * a := hx
    _ = (a * x - 0 * t 0) * a := by simp
    _ = a * (x - (1 - x * a) * t 0) * a := by
      rw [mul_sub, ← mul_assoc a (1 - x * a), hzero, zero_mul]

/-- A von Neumann-regular ring with supplied least stable range one is
unit-regular. -/
theorem isUnitRegular_of_stableRange_one
    (hreg : IsVonNeumannRegular R)
    (hsr : IsStableRange R 1) :
    IsUnitRegular R :=
  isUnitRegular_of_stableRangeCondition_one hreg hsr.1

/-- For a von Neumann-regular ring, unit-regularity is equivalent to Bass's
condition `(S_1)`. -/
theorem isUnitRegular_iff_stableRangeCondition_one
    (hreg : IsVonNeumannRegular R) :
    IsUnitRegular R ↔ StableRangeCondition R 1 :=
  ⟨IsUnitRegular.stableRangeCondition_one,
    isUnitRegular_of_stableRangeCondition_one hreg⟩

/-- For a nontrivial von Neumann-regular ring, unit-regularity is equivalent
to having least Bass stable range one. -/
theorem isUnitRegular_iff_stableRange_one [Nontrivial R]
    (hreg : IsVonNeumannRegular R) :
    IsUnitRegular R ↔ IsStableRange R 1 :=
  ⟨IsUnitRegular.stableRange_one, isUnitRegular_of_stableRange_one hreg⟩

end Bass
